service: transcribe-twilio

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

resources: # CloudFormation template syntax
  Resources:
    recordingStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: transcribe-twilio-dev-content
        # AccessControl: PublicReadWrite

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "*"
      Resource:
        Fn::GetAtt:
          - recordingStorage
          - Arn

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

